# 头部菜单，title: link
menu:
  Whoami: /whoami
  Github: https://github.com/bianjiashuai
  Gitee: https://gitee.com/bianjiashuai

# 是否显示目录
TOC: false

# 是否自动播放音乐
autoplay: false

# 默认音乐
mp3:
  - https://link.hhtjim.com/163/1330348068.mp3
  - https://link.hhtjim.com/163/449818741.mp3
  - https://link.hhtjim.com/163/32507038.mp3
  - https://link.hhtjim.com/163/108914.mp3

# 首页封面图, 为空时取文章的cover作为封面
welcome_cover: # /img/welcome-cover.jpg

# 默认文章封面图
cover: /img/default/cover.jpg

# 是否关闭默认滚动条
scrollbar: true

# Gitalk 评论插件（https://github.com/gitalk/gitalk）
gitalk:
    # 是否自动展开评论框
    autoExpand: false
    # 应用编号
    clientID: '74aab94381e465bd5728'
    # clientID: ''
    # 应用秘钥
    clientSecret: '1c859fa07dad32695c41c83dc8b8acc9e1d73652'
    # clientSecret: ''
    # issue仓库名
    repo: 'bianjiashuai.github.io'
    # Github名
    owner: 'bianjiashuai'
    # Github名
    admin: ['bianjiashuai']
    # Ensure uniqueness and length less than 50
    id: location.pathname
    # Facebook-like distraction free mode
    distractionFreeMode: false

# 网站关键字
keywords: Fechin

# 要使用google_analytics进行统计的话，这里需要配置ID
google_analytics:

# 网站ico
favicon: /img/favicon.png

# rss文件
rss: atom.xml
